import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* Brand primitives — prefer alias tokens in components */
        papaya: {
          100: 'var(--papaya-100)',
          200: 'var(--papaya-200)',
          300: 'var(--papaya-300)',
          400: 'var(--papaya-400)',
          500: 'var(--papaya-500)',
          600: 'var(--papaya-600)',
          700: 'var(--papaya-700)',
          800: 'var(--papaya-800)',
          900: 'var(--papaya-900)',
        },
        green: {
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
          800: 'var(--green-800)',
          900: 'var(--green-900)',
        },
        red: {
          100: 'var(--red-100)',
          200: 'var(--red-200)',
          300: 'var(--red-300)',
          400: 'var(--red-400)',
          500: 'var(--red-500)',
          600: 'var(--red-600)',
          700: 'var(--red-700)',
          800: 'var(--red-800)',
          900: 'var(--red-900)',
        },
        blue: {
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          300: 'var(--blue-300)',
          400: 'var(--blue-400)',
          500: 'var(--blue-500)',
          600: 'var(--blue-600)',
          700: 'var(--blue-700)',
          800: 'var(--blue-800)',
          900: 'var(--blue-900)',
        },
        yellow: {
          100: 'var(--yellow-100)',
          200: 'var(--yellow-200)',
          300: 'var(--yellow-300)',
          400: 'var(--yellow-400)',
          500: 'var(--yellow-500)',
          600: 'var(--yellow-600)',
          700: 'var(--yellow-700)',
          800: 'var(--yellow-800)',
          900: 'var(--yellow-900)',
        },
        grey: {
          50: 'var(--grey-50)',
          100: 'var(--grey-100)',
          200: 'var(--grey-200)',
          300: 'var(--grey-300)',
          400: 'var(--grey-400)',
          500: 'var(--grey-500)',
          600: 'var(--grey-600)',
          700: 'var(--grey-700)',
          800: 'var(--grey-800)',
          900: 'var(--grey-900)',
        },
        /* Semantic aliases — primary use in components */
        surface: {
          DEFAULT: 'var(--surface-default)',
          page: 'var(--surface-page)',
          'page-secondary': 'var(--surface-page-secondary)',
          'default-secondary': 'var(--surface-default-secondary)',
          primary: {
            DEFAULT: 'var(--surface-primary-default)',
            hover: 'var(--surface-primary-default-hover)',
            subtle: 'var(--surface-primary-default-subtle)',
            'subtle-hover': 'var(--surface-primary-default-subtle-hover)',
          },
          error: {
            DEFAULT: 'var(--surface-error-default)',
            hover: 'var(--surface-error-default-hover)',
            subtle: 'var(--surface-error-default-subtle)',
          },
          information: {
            DEFAULT: 'var(--surface-information-default)',
            hover: 'var(--surface-information-default-hover)',
            subtle: 'var(--surface-information-default-subtle)',
          },
          warning: {
            DEFAULT: 'var(--surface-warning-default)',
            hover: 'var(--surface-warning-default-hover)',
            subtle: 'var(--surface-warning-default-subtle)',
          },
          success: {
            DEFAULT: 'var(--surface-success-default)',
            hover: 'var(--surface-success-default-hover)',
            subtle: 'var(--surface-success-default-subtle)',
          },
          disabled: 'var(--surface-disabled-disabled)',
        },
        text: {
          heading: 'var(--text-default-heading)',
          body: 'var(--text-default-body)',
          caption: 'var(--text-default-caption)',
          placeholder: 'var(--text-default-placeholder)',
          'on-color': {
            heading: 'var(--text-on-color-heading)',
            body: 'var(--text-on-color-body)',
            caption: 'var(--text-on-color-caption)',
          },
          primary: {
            DEFAULT: 'var(--text-primary-default)',
            hover: 'var(--text-primary-default-hover)',
            'on-color': 'var(--text-primary-on-color)',
          },
          error: {
            DEFAULT: 'var(--text-error-default)',
            hover: 'var(--text-error-default-hover)',
          },
          information: {
            DEFAULT: 'var(--text-information-default)',
            hover: 'var(--text-information-default-hover)',
          },
          warning: {
            DEFAULT: 'var(--text-warning-default)',
            hover: 'var(--text-warning-default-hover)',
          },
          success: {
            DEFAULT: 'var(--text-success-default)',
            hover: 'var(--text-success-default-hover)',
          },
          disabled: 'var(--text-disabled-default)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          secondary: 'var(--border-default-secondary)',
          primary: {
            DEFAULT: 'var(--border-primary-default)',
            hover: 'var(--border-primary-default-hover)',
            subtle: 'var(--border-primary-default-subtle)',
            focus: 'var(--border-primary-focus)',
          },
          error: {
            DEFAULT: 'var(--border-error-default)',
            focus: 'var(--border-error-focus)',
          },
          disabled: 'var(--border-disabled-disabled)',
        },
        white: 'var(--white)',
        dark: 'var(--dark)',
        /* Design system — neutral scale for SaaS UI */
        neutral: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
          950: '#0a0a0a',
        },
      },
      fontFamily: {
        sans: ['var(--font-primary)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Cousine', 'Fira Code', 'Cascadia Code', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        /* Prism type scale */
        'h1': ['var(--h1-size)', { lineHeight: 'var(--h1-lh)', letterSpacing: 'var(--h1-ls)' }],
        'h2': ['var(--h2-size)', { lineHeight: 'var(--h2-lh)', letterSpacing: 'var(--h2-ls)' }],
        'h3': ['var(--h3-size)', { lineHeight: 'var(--h3-lh)', letterSpacing: 'var(--h3-ls)' }],
        'h4': ['var(--h4-size)', { lineHeight: 'var(--h4-lh)', letterSpacing: 'var(--h4-ls)' }],
        'h5': ['var(--h5-size)', { lineHeight: 'var(--h5-lh)', letterSpacing: 'var(--h5-ls)' }],
        'h6': ['var(--h6-size)', { lineHeight: 'var(--h6-lh)', letterSpacing: 'var(--h6-ls)' }],
        'body-lg': ['var(--body-lg-size)', { lineHeight: 'var(--body-lg-lh)' }],
        'body': ['var(--body-size)', { lineHeight: 'var(--body-lh)' }],
        'small': ['var(--small-size)', { lineHeight: 'var(--small-lh)', letterSpacing: 'var(--small-ls)' }],
        'caption': ['var(--caption-size)', { lineHeight: 'var(--caption-lh)', letterSpacing: 'var(--caption-ls)' }],
      },
      spacing: {
        's-100': 'var(--s-100)',
        's-200': 'var(--s-200)',
        's-300': 'var(--s-300)',
        's-400': 'var(--s-400)',
        's-500': 'var(--s-500)',
        's-600': 'var(--s-600)',
        's-700': 'var(--s-700)',
        's-800': 'var(--s-800)',
        's-900': 'var(--s-900)',
        's-1000': 'var(--s-1000)',
        's-1100': 'var(--s-1100)',
        's-1200': 'var(--s-1200)',
        's-1300': 'var(--s-1300)',
        's-1400': 'var(--s-1400)',
      },
      maxWidth: {
        content: 'var(--max-w-content)',
        prose: 'var(--max-w-prose)',
        narrow: 'var(--max-w-narrow)',
        slim: 'var(--max-w-slim)',
      },
      borderRadius: {
        'prism-100': 'var(--br-100)',
        'prism-200': 'var(--br-200)',
      },
      borderWidth: {
        'prism-25': 'var(--bw-25)',
        'prism-100': 'var(--bw-100)',
      },
      boxShadow: {
        'accent': '0 4px 20px rgba(236, 78, 11, 0.25)',
      },
    },
  },
  plugins: [],
}

export default config
